### ISSUE TITLE
Ability to have Auto-Reload and Slow Reload on empty

### ISSUE THREAD

**Issue by trexx45** [argonlefou/Hotd3pc_ArcadeMod#3]
These are not really big issues, but mostly a request:
- Being able to change from Auto-Reloading to Manual 
- Slow reload (40 frames) when the main weapon is empty for even more Arcade parity! (Can only be active when Manual-Reloading is on)

Thank you for your amazing work!

**Comment by argonlefou** [comment]
>     * Being able to change from Auto-Reloading to Manual
Hmm...I'm not sure to understand your request as auto-reload (when clip is empty) is disabled with this mod

>     * Slow reload (40 frames) when the main weapon is empty for even more Arcade parity! (Can only be active when Manual-Reloading is on)
Interresting question....so you mean that in the real arcade version of the game, the reload animation is slower when you pump with 0 bullet in the clip than if you pump with some bullets left ?

**Comment by trexx45** [comment]
**Being able to change from Auto-Reloading to Manual**
- Having the ability to turn on or off the option. For context, I play on Oculus to simulate a lightgun experience, and reloading takes me about 1.5 seconds to do efficiently. Having auto reloading would help a lot!

**Slow reload (40 frames) when the main weapon is empty for even more Arcade parity! (Can only be active when Manual-Reloading is on)**
- Yes! Both the Arcade and the PS3 versions have this detail when running out of ammo. And I made the comparison, and the task takes about 40 frames.

**Comment by argonlefou** [comment]
> **Being able to change from Auto-Reloading to Manual**
> 
>     * Having the ability to turn on or off the option. For context, I play on Oculus to simulate a lightgun experience, and reloading takes me about 1.5 seconds to do efficiently. Having auto reloading would help a lot!

Ok so you want to put back auto-reload for your needs, instead of normal arcade manual reload ?
This is not the aim of that mod, but you'll be able to get that by modifying the source and compiling the code for your needs.
I'll explain what to do and will compile a version when this ticket will be over, but I won't add options and change the GUI for such a specific need

> **Slow reload (40 frames) when the main weapon is empty for even more Arcade parity! (Can only be active when Manual-Reloading is on)**
> 
>     * Yes! Both the Arcade and the PS3 versions have this detail when running out of ammo. And I made the comparison, and the task takes about 40 frames.

This is interresting...do you have any video footage of this ? (Arcade, not PS3). 
I know ps3 version has the PC-alike slow 40frame reload animation, but - and unfortunatelly I do not own any Hotd3 arcade system to test it myself - every arcade video footage I found does not seem to change the reload speed between empty ammo or not :  
https://www.youtube.com/watch?v=iZlh8qDkzwo  
https://www.youtube.com/watch?v=aOf28-VJeu0

I'm pretty sure videos are not good enough to precisely measure the frame numbers to reload, but event if there's a difference it's obviously way faster than the 40frame slow animation

**Comment by trexx45** [comment]
I was not able to get my hands on better footage that doesn't feature a player shooting fast enough to see the frame. But I should actually apologize, because I made a mistake. It is actually 15-17 frames, instead of 40. Sorry for any misconceptions!

VIDEO FOOTAGE: https://www.youtube.com/watch?v=drJFPDDArts&t=778s

Finally, I would appreciate if you could teach me how to add auto-reload through this mod source!

Thank you for your help!

**Comment by argonlefou** [comment]
No worries, it could have been a feature from a different game version. 
As for exemple : the video you posted (thanks, I didn't found this one with full gameplay) displays the score on the upper part of the player UI, whereas the one I found didn't.

The actual version of the Mod uses a 17-frame-delay for reload (between the command and the ammo refill) even if the gun animation is a bit faster (it's tied to how I managed to alter the different 3D objects animation without messing too much with the initial design).....so this can stay unmodified as we can clearly see on your video no differences between empty/not empty clip reload

As for removing the no-auto-reload feature, if you want to change the code and recompile it : 
- Edit the following file : `/Hotd3Arcade_Launcher/Hotd3Arcade_Launcher.cs`
- Go to line `462` (the line should be : `Mod_NoAutoReload();`)
- Comment or remove the line
- Compile

I'm joining a compiled version for you
[Hotd3Arcade_Launcher_noautoreload.zip](https://github.com/argonlefou/Hotd3pc_ArcadeMod/files/10792394/Hotd3Arcade_Launcher_noautoreload.zip)
