### ISSUE TITLE
Add keymap "6" for coins in addition to "5"

### ISSUE THREAD

**Issue by zaphod4254** [argonlefou/Hotd3pc_ArcadeMod#7]
Minor enhancement request.  Add a keymapping of 6 to insert coins in addition to 5.

I run this in an arcade cabinet with real coin slots, wired to an Ultimarc I-PAC for coin Player 1 ("5") and coin Player 2 ("6").  (I keep a tub of tokens around for guests to play free, but keeps the real arcade feel.)

Most games (granted, not all, but most) will trigger coins by using 5 or 6.  I.e., with the cabinet, when inserting coins into either coin slot.

**Comment by argonlefou** [comment]
The game (and the mod) does not support separated coins for P1 / P2, both player are using the same credits pool.

Adding that key - although beeing doable - is not necessary as far as the game itself is concerned.

Before tweaking the mod even more, and as you are using I-PAC to handle you coin slots : I guess you're using the I-PAC as keyboard device to outputs `5` or `6` key press on coin ?

In that case,  could you try to run a simple AHK script to remap the key 6 to the key 5 ? (so that your coin slot2 can increments credits as well)

**Comment by zaphod4254** [comment]
You are correct.  It's not about "separate" coins for P1 & P2.  It's just so that "6" will also trigger a coin for the shared coin quantity.  The AHK script would likely work, but I can't figure out how to set this up in LaunchBox.  There is no per-game AHK script configuration in LaunchBox.  I'm loosely familiar with AHK, but I've never worked with it outside of what LB has built in.

**Comment by argonlefou** [comment]
I'm sorry, I do not use Launchbox at all and have no knowledge about it.
But I've read a lot of people using AHK with it.

As for the AHK scripts, I successfully tested these 2 very simple scipts (using a regular Keyboard) : 
1st one based on the ScanCode of the key 
`SC007::send {SC006}`

And the second one based on the Virtual KeyCode of the Key
`VK036::VK035`

To create a AHK script out of LaunchBox : 
- Just create some text file, put one of those 2 line in it and save it as `something.ahk`
- Run it by double clicking on it
- In your windows tray (bottom right corner, near clock) you'll see a green "H" icon : right-click on it and `Exit` to terminate

So I would advise you to test those options with your I-PAC (running the game directly, without using LauchBox) in order to find the suitable and working script for your needs.

Then, once this first step is achieved, you will be able to seek help from LaunchBox users for how to run this script (that you know is working, it's the important part)
