### ISSUE TITLE
[Feature request] Trigger "Reload" voice only after you fire empty gun as an option.

### ISSUE THREAD

**Issue by RiasatSalminSami** [argonlefou/Hotd3pc_ArcadeMod#9]
That's how it has been for the previous House of Dead games. In HOD3, right after you run out of bullets- the reload voice gets triggered. So throughout the whole game you keep hearing "Reload, Reload" and this turns into annoyance real quick.

Only way to not trigger the sound is by only shooting 5 shots instead of 6 shots. But one single shot can mean getting hit vs not getting hit. When going to a high score run [on hard difficulty], most of the time you have to fire 6 shots every time to kill the hoards before they get to attack you. Even on 1 vs 2 zombie scenarios, you are likely to shoot 3 shots on each of them quickly to get "Excellent" grade. 

There might be a bruteforce way currently by just deleting the "reload.aif" file in the media folder. But then you wont hear the reload sound when you shoot empty gun. 

There also seems to be "reload_02.aif" which tells you press the reload button. This might have been similar to HOD1 and 2 where if you spammed fire on empty gun repeatedly, the game would tell you to shoot outside of the screen. However, I have not been able to trigger this sound in the game at all even when I kept spamming empty gun several times. 

So yeah, having this as an option would make the game feel less annoying and the game will only tell you to reload if you accidentally fire empty gun instead.

**Comment by argonlefou** [comment]
Hello, and thanks for the report.

The purpose of the launcher is to mimic - as accurate as possible - the arcade version.
Unfortunately, I do not own that arcade version - and have no access to it - so most of the decisions were made using some (very rare!) youtube footage of the real cabinet. 

[That one](https://www.youtube.com/watch?v=FQv1OFvLs9I) in particular helped me to get few info on the SFX, but still....shoots and reload happen so fast it was hard to determine how exactly it should have been.

Looking back at HOD2 and HOD1 is indeed a great idea ! I honestly don't know why it didn't cross my mind back then 😯

So I just pushed a new v7.0 update removing that SFX when the clip goes empty, keeping the SFX when the player hits the trigger without ammo 👍

As for the "reload_02.aif", there are lot of files that are left unused by the exe
IMO, it may be because they kept the file structure from Arcade/XBOX or whatever other version, while changing the code as they needed.
Some of the files were not even loaded by the code, like the coin sound.... I had to replace one unused soud reference to point it to the right file for my needs....

The "reload_02.aif" has a reference, and can be easily played with the mod.
I may be wrong, but I find it kind of odd to ask the player to press the reload button, instead of pumping the gun. Maybe that file was used in Xbox or Wii version ?
HOD2 is pretty clear with that, by yelling "Shoot out of the screen"

But if someone as the real Arcade game or some video footage of it, I will be able to add that SFX if the player keeps hitting the trigger without Ammo

**Comment by argonlefou** [comment]
Also found a ["new" footage](https://youtu.be/SxRS057QFTA?t=545) I didn't ran into when creating that mod.

We can clearly hear at 09:06 the "Re-Re-Reload !"  SFX chain without any other different SFX

On the other hand, we can also see that the RELOAD sprite has a lower "Pump the gun" sprite appearing below after a certain time

**Comment by RiasatSalminSami** [comment]
I will see if I can get my hands to the Chihiro files. I had Virtua cop 3 and managed to run that on Xemu and CXBXr emulators. So maybe the og chihiro version of hod3 might be bootable on these emulators too.  Just having the files should give us some clue.

By the way, I also have the Xbox port of hod3 and the PC port is missing a lot more graphical effects from both xbox and chihiro versions:

Xbox:
-When Death first bursts out of the ground in 2nd stage, there is motion blur effect on Xbox which is missing on pc.
-Lighting on Fool boss fight also looks different.

I have been playing the xbox version through backwards compatibility on my xbox 360, so there might be missing effects. I will try the game on xemu to see if there are even more missing effects on the pc port.

^These effects are most likely present on chihiro version as well.

I don't know if it's his camera or monitor but it looks like when the zombies are walking, they have motion blur. Cannot confirm this since the footage was not high quality. 

He also didn't pull the trigger once the "Pump the shotgun" sprite appeared below the reload text. So we can't know if the game has voice saying "Pump the shotgun". Only way to find out is by looking at the game files.


Also the chihiro port seems to have perfect framepacing. You can see the game runs almost stutterless. But the pc port seems to suffer from minor stutters frequently which isn't game breaking but it's noticeable.

**Comment by argonlefou** [comment]
> I will see if I can get my hands to the Chihiro files. I had Virtua cop 3 and managed to run that on Xemu and CXBXr emulators. So maybe the og chihiro version of hod3 might be bootable on these emulators too. Just having the files should give us some clue.

The arcade dump has a "Pump the shotgun" audio file, amongst a lot of other reload SE (like "shoot out of the screen" or "press the reload button"
If you manage to extract the Chihiro ROM, you'll find them packed in the `VOICE_US.AFS` file (precisely, `VOICE_US_00818.adx`)

> By the way, I also have the Xbox port of hod3 and the PC port is missing a lot more graphical effects from both xbox and chihiro versions:
> 
> Xbox: -When Death first bursts out of the ground in 2nd stage, there is motion blur effect on Xbox which is missing on pc. -Lighting on Fool boss fight also looks different.
> 
> I have been playing the xbox version through backwards compatibility on my xbox 360, so there might be missing effects. I will try the game on xemu to see if there are even more missing effects on the pc port.
> 
> ^These effects are most likely present on chihiro version as well.
> 
> I don't know if it's his camera or monitor but it looks like when the zombies are walking, they have motion blur. Cannot confirm this since the footage was not high quality.
> 
> He also didn't pull the trigger once the "Pump the shotgun" sprite appeared below the reload text. So we can't know if the game has voice saying "Pump the shotgun". Only way to find out is by looking at the game files.
> 
> Also the chihiro port seems to have perfect framepacing. You can see the game runs almost stutterless. But the pc port seems to suffer from minor stutters frequently which isn't game breaking but it's noticeable.

Unfortunately, except a top notch emulation from the oroginal dump, adding all those effect and enhencing the PC game engine is something way out of my league ...
I'm merely replacing sprites and changing some bytes here and there, to make it close to the arcade feeling but still....it will never be as good as a dedicated machine (unfortunatelly)

**Comment by RiasatSalminSami** [comment]
You've already massively improved the pc experience with your modifications. I'm really grateful for that.

If the arcade dump has those audio files, is it possible to put those audio files on pc? 

The last thing holding back the pc port is lack of mouse support for player 2 at all. All the previous pc ports could be played with mouse as p2 but on hod3 you cant set the input of p2 as mouse at all.

**Comment by argonlefou** [comment]
> You've already massively improved the pc experience with your modifications. I'm really grateful for that.
> 
> If the arcade dump has those audio files, is it possible to put those audio files on pc?

Well, it turns out you also have those file available in the PC version of the game :
You can extract the 833 *.adx sound files from the `/fs/VOICE_US.AFS` resource file with [ADXutil](http://www.geocities.ws/sakura_br/) for example.

That `VOICE_US.AFS` file is exactly the same than the one found in the arcade dump of the game.
The arcade version just rely on the `FS` and `MVI` folders (with japanese video also, not only english ones), there is no `fs2` or `media`
So again, it's hard to know how exactly the PC version is mixing assets from the arcade and from the specific PC folders.

But, if you want to use one of this sound file to replace any of the *.aif files used by the game in the `/media/` folder, you just need to convert the wanted ADX file to a simple WAV format, and rename it with AIF extention.
Note that ADXUtil has an option to extract tracks directly in WAV format

Now for **_adding_** more sound effect (like the coin sound or reload sound), it's a little bit more complicated as - as far as I was able to dig - the game is loading a pre-determined list of sound file to memory. And we can't access the filename directly to play the file on the disk.

> The last thing holding back the pc port is lack of mouse support for player 2 at all. All the previous pc ports could be played with mouse as p2 but on hod3 you cant set the input of p2 as mouse at all.

Well, even if you could set P2 input as mouse, it would be impossible to have mouse for P1 at the same time (it would, but controls would be the same for both players)
RawInput handling to use multiple mice is not even a part of most recent project in 2024.....this has been the whole purpose of my main project for years now [(DemulShooter)](https://github.com/argonlefou/DemulShooter/)

**Comment by RiasatSalminSami** [comment]
Aye, understood. Still having the ability to play as p2 with mouse would be nice [for doing solo p2 playthrough].

Damn I didn't realize you were the same person. I never managed to get my mouse working with demul shooter. The cursor seems to remain stuck on top left corner and only mouse buttons work.

Btw, after playing the xbox port of hod again, I realized there are even more missing sound effects on the pc port. When Death emerges out of the ground on stage 2, there is a loud burst sound which is completely missing on pc port. Looks like there might be lot more differences that we will find out overtime. I should probably create a separate thread.

**Comment by argonlefou** [comment]
> Damn I didn't realize you were the same person. I never managed to get my mouse working with demul shooter. The cursor seems to remain stuck on top left corner and only mouse buttons work.
> 

DemulShooter is not designed to work with a simple regular mouse, it needs an absolute-coordinate-mouse-device (i.e lightgun, touch screen, etc ..) or a gamepad.

But there is some work around, as long as you just want to play solo :

1) Set your device to your mouse in DemulShooter_GUI for the player you want.
Only buttons will work and cirsor will be stuck as you already saw in the GUI.

2) When you run DemulShooter.exe, add the `-usesinglemouse` option in the command line.
This will make DemulShooter to use the window cursor instead of mouse coordinates.
